const translations = {
    mr: {
        navTitle: "अस्मिता मराठी नाट्य सेवा संस्था",
        home: "मुख्य",
        about: "आमच्याबद्दल",
        events: "कार्यक्रम", 
        gallery: "गॅलरी",
        contact: "संपर्क",
        ourFounders: "आमचे संस्थापक",
        ourFoundation: "आमची संस्था",
        foundationText: "दोन वर्षांपूर्वी स्थापन झालेली अस्मिता मराठी नाट्य सेवा संस्था मराठी भाषा नव्या पिढीमध्ये आणि व्यापक समाजामध्ये जपून ती वृद्धिंगत करण्याच्या उत्कट इच्छेतून जन्माला आली. मराठी कला आणि नाट्य हळूहळू आपले प्रेक्षक गमावत आहेत हे लक्षात आल्यावर, आमच्या संस्थापकांनी आपली मातृभाषा—मराठी—याची समृद्धता प्रभावी नाटकं, एकांकिका आणि सादरीकरणाच्या माध्यमातून जिवंत ठेवण्यासाठी ही संस्था समर्पित केली.",
        ourApproach: "आमचा दृष्टिकोन",
        approachText: "आम्ही नाट्यकला, कार्यशाळा (workshops), रंगमंचीय प्रयोग आणि पथनाट्ये (street plays) यावर लक्ष केंद्रित करतो—विविध उत्सव, समारंभ आणि मागणीनुसार आयोजित कार्यक्रमांमध्ये—प्रत्येक संभाव्य माध्यमाचा उपयोग करून मराठी भाषा अर्थपूर्ण आणि आकर्षक बनवतो, विशेषतः लहान मुले आणि तरुण प्रेक्षकांसाठी. आमची पोहोच शालेय विद्यार्थी, महाविद्यालयीन तरुण, नाट्यप्रेमी, ग्रामीण समाज आणि जगभरातील मराठी भाषिक प्रेक्षकांपर्यंत आहे. यामुळे आम्ही संस्कृती आणि वारसा यांच्याशी असलेले घट्ट नाते दृढ करत आहोत.",
        ourImpact: "आमचा प्रभाव आणि ध्येय",
        impactText: "केवळ दोन वर्षांत, आम्ही अनेक शहरांमध्ये प्रयोग केले आहेत, नवीन कलाकारांचे आमच्या संस्थेत स्वागत केले आहे आणि सहभागी कलाकार तसेच संस्थेचा टिकाऊ (sustainably) विकास सुनिश्चित केला आहे. सादरीकरणांपलीकडे, आम्ही सामाजिक जाणीव निर्माण करण्यासाठी, कलागुणांना वाव देण्यासाठी आणि मराठी नाटकांबद्दलचे प्रेम दूरवर पसरवण्यासाठी सक्रियपणे योगदान देत आहोत. मराठी नाट्यकला आणि संस्कृतीचे जतन करणे, हे आमचे ध्येय आहे. संपूर्ण भारतातील सर्व मूळ मराठी भाषिकांच्या हृदयाला स्पर्श करण्यासाठी आणि आमच्या भाषेचे व कलांचे सौंदर्य पुढील पिढ्यांना प्रेरणा देत राहील हे सुनिश्चित करण्यासाठी आम्ही आमच्या कार्याचा विस्तार करत आहोत.",
        president: "अध्यक्ष",
        secretary: "सचिव",
        member: "सदस्य",
        girishDesc: "मराठी नाट्यकला आणि सांस्कृतिक संवर्धनाच्या उत्कटतेने संस्थेचे नेतृत्व करत आहेत.",
        sudheerDesc: "संस्थेच्या कार्यक्रमांचे व्यवस्थापन आणि समुदायात नाट्यकलेला प्रोत्साहन देत आहेत.",
        neetaDesc: "सांस्कृतिक कार्यक्रमांना पाठिंबा देत आणि नाट्यकलेत महिलांच्या सहभागाला प्रोत्साहन देत आहेत.",
        title: "अस्मिता मराठी नाट्य सेवा संस्था<br>मराठी रंगभूमी",
        location: "अस्मिता मराठी नाट्य सेवा संस्था, उज्जैन (म.प्र.)",
        regNo: "नोंदणी क्रमांक: 07/33/01/18504/24",
        description: "सामाजिक, कौटुंबिक आणि परिस्थितिजन्य नाटकांच्या माध्यमातून सांस्कृतिक संवर्धन",
        joinUs: "आमच्यात सामील व्हा",
        viewPrograms: "कार्यक्रम पहा",
        aboutUsTitle: "आमच्याबद्दल",
        aboutUsText: "दोन वर्षांपूर्वी स्थापन झालेली अस्मिता मराठी नाट्य सेवा संस्था मराठी भाषा नव्या पिढीमध्ये आणि व्यापक समाजामध्ये जपून ती वृद्धिंगत करण्याच्या उत्कट इच्छेतून जन्माला आली. मराठी कला आणि नाट्य हळूहळू आपले प्रेक्षक गमावत आहेत हे लक्षात आल्यावर, आमच्या संस्थापकांनी आपली मातृभाषा—मराठी—याची समृद्धता प्रभावी नाटकं, एकांकिका आणि सादरीकरणाच्या माध्यमातून जिवंत ठेवण्यासाठी ही संस्था समर्पित केली.",
        aboutUsText2: "आम्ही नाट्यकला, कार्यशाळा (workshops), रंगमंचीय प्रयोग आणि पथनाट्ये (street plays) यावर लक्ष केंद्रित करतो—विविध उत्सव, समारंभ आणि मागणीनुसार आयोजित कार्यक्रमांमध्ये—प्रत्येक संभाव्य माध्यमाचा उपयोग करून मराठी भाषा अर्थपूर्ण आणि आकर्षक बनवतो, विशेषतः लहान मुले आणि तरुण प्रेक्षकांसाठी. आमची पोहोच शालेय विद्यार्थी, महाविद्यालयीन तरुण, नाट्यप्रेमी, ग्रामीण समाज आणि जगभरातील मराठी भाषिक प्रेक्षकांपर्यंत आहे. यामुळे आम्ही संस्कृती आणि वारसा यांच्याशी असलेले घट्ट नाते दृढ करत आहोत.",
        aboutUsText3: "केवळ दोन वर्षांत, आम्ही अनेक शहरांमध्ये प्रयोग केले आहेत, नवीन कलाकारांचे आमच्या संस्थेत स्वागत केले आहे आणि सहभागी कलाकार तसेच संस्थेचा टिकाऊ (sustainably) विकास सुनिश्चित केला आहे. सादरीकरणांपलीकडे, आम्ही सामाजिक जाणीव निर्माण करण्यासाठी, कलागुणांना वाव देण्यासाठी आणि मराठी नाटकांबद्दलचे प्रेम दूरवर पसरवण्यासाठी सक्रियपणे योगदान देत आहोत.",
        aboutUsText4: "मराठी नाट्यकला आणि संस्कृतीचे जतन करणे, हे आमचे ध्येय आहे. संपूर्ण भारतातील सर्व मूळ मराठी भाषिकांच्या हृदयाला स्पर्श करण्यासाठी आणि आमच्या भाषेचे व कलांचे सौंदर्य पुढील पिढ्यांना प्रेरणा देत राहील हे सुनिश्चित करण्यासाठी आम्ही आमच्या कार्याचा विस्तार करत आहोत.",
        upcomingEvents: "आगामी कार्यक्रम",
        eventsSubtitle: "आमचे नवीनतम नाट्य प्रयोग आणि सांस्कृतिक कार्यक्रम",
        eventTypes: "कार्यक्रम प्रकार",
        theatrePerformances: "नाट्य प्रयोग",
        theatreDesc: "पारंपरिक आणि आधुनिक मराठी नाटके",
        workshops: "कार्यशाळा",
        workshopDesc: "अभिनय आणि नाट्य तंत्र शिकवणे",
        festivalPrograms: "उत्सव कार्यक्रम",
        festivalDesc: "विशेष प्रसंगी सांस्कृतिक सादरीकरण",
        gallerySubtitle: "आमच्या संस्मरणीय क्षणांची झलक",
        videoGallery: "व्हिडिओ गॅलरी",
        sanskarPlay: "नाट्य प्रयोग - \"संस्कार\"",
        actingWorkshop: "अभिनय कार्यशाळा",
        culturalProgram: "सांस्कृतिक कार्यक्रम",
        dharAugTitle: "धार - ऑगस्ट 2025",
        ujjainSepTitle: "उज्जैन - सप्टेंबर 2025",
        noEventsMessage: "अद्याप कोणतेही आगामी कार्यक्रम नियोजित नाहीत",
        checkBackMessage: "कृपया अपडेट्ससाठी पुन्हा पहा",
        emailUs: "आम्हाला ईमेल करा",
        sendQueries: "आम्हाला तुमचे प्रश्न पाठवा",
        sendEmail: "ईमेल पाठवा",
        connectWithUs: "आमच्याशी जोडले रहा",
        chatInstantly: "आमच्या टीमशी तात्काळ चॅट करा",
        visitUs: "आमच्याकडे या",
        findLocation: "आमचे ठिकाण शोधा",
        getDirections: "दिशा मिळवा",
        applyNow: "आताच अर्ज करा",
        programGallery: "कार्यक्रम गॅलरी",
        contactUs: "संपर्क करा",
        yourName: "आपले नाव",
        emailAddress: "ईमेल पत्ता",
        message: "संदेश",
        sendMessage: "संदेश पाठवा",
        mainPages: "मुख्य पाने",
        extras: "अतिरिक्त",
        privacyPolicy: "गोपनीयता धोरण",
        adminPanel: "अॅडमिन पॅनल",
        contactInfo: "संपर्क माहिती", 
        copyright: "© 2024 अस्मिता मराठी नाट्य सेवा संस्था, उज्जैन म.प्र. सर्व हक्क राखीव.",
        privacy: "गोपनीयता",
        help: "सहाय्य",
        performances: "प्रदर्शने",
        artists: "कलाकार",
        experience: "वर्षांचा अनुभव",
        // About Page
        aboutTitle: "परिचय - अस्मिता मराठी नाट्य सेवा संस्था",
        aboutHeroTitle: "आमच्याबद्दल",
        aboutHeroSubtitle: "मराठी नाट्यकलेची समृद्ध परंपरा पुढे नेणे",
        ourHistory: "आमचा इतिहास",
        historyText: "अस्मिता मराठी नाट्य सेवा संस्था उज्जैनमध्ये 2018 मध्ये स्थापन झाली. आमची सुरुवात मराठी भाषा आणि संस्कृतीच्या संवर्धनाच्या उद्देशाने झाली. गेल्या काही वर्षांत आम्ही अनेक यशस्वी नाटके सादर केली आहेत आणि स्थानिक कलाकारांना मंच प्रदान केले आहे. आमच्या प्रयत्नांमुळे उज्जैनमध्ये मराठी नाट्यकलेला नवीन दिशा मिळाली आहे.",
        ourMission: "आमचे उद्दिष्ट",
        ourVision: "आमची दृष्टी",
        missionText: "मराठी भाषा आणि संस्कृती जिवंत ठेवणे, नवीन प्रतिभांना मंच प्रदान करणे, आणि समाजात कलात्मक चेतना विकसित करणे हे आमचे मुख्य उद्दिष्ट आहे.",
        visionText: "असा समाज निर्माण करणे जिथे मराठी नाट्य कला फुलून फळून वाढेल आणि नवी पिढी या समृद्ध वारशाशी जुळेल. आम्हाला वाटते की प्रत्येक व्यक्तीने कलेच्या माध्यमातून आपली अभिव्यक्ती करावी.",
        ourTeam: "आमची टीम",
        founder: "संस्थापक आणि संचालक",
        artisticDirector: "कलात्मक संचालक",
        musicDirector: "संगीत संचालक",
        // Contact Page
        contactTitle: "संपर्क - अस्मिता मराठी नाट्य सेवा संस्था",
        contactHeroTitle: "संपर्क करा",
        contactHeroSubtitle: "आमच्याशी जुळा आणि मराठी नाट्य कलेचा भाग बना",
        contactInfoTitle: "संपर्क माहिती",
        address: "पत्ता",
        phone: "फोन",
        email: "ईमेल",
        timing: "वेळ",
        timingDetails: "सोमवार - शनिवार<br>सकाळी 10:00 - संध्याकाळी 6:00",
        sendMessageTitle: "संदेश पाठवा",
        yourPhone: "फोन नंबर",
        selectSubject: "विषय निवडा",
        subjectMembership: "सदस्यता",
        subjectPerformance: "प्रदर्शन",
        subjectWorkshop: "कार्यशाळा",
        subjectCollaboration: "सहयोग",
        subjectOther: "इतर",
        ourLocation: "आमचे स्थान",
        locationOnMap: "उज्जैन, मध्य प्रदेश मध्ये आमचे स्थान",
        joinUsTitle: "आमच्या नाट्य कुटुंबात सामील व्हा",
        joinUsDescription: "तुम्हाला मराठी नाट्यकलेची आवड आहे का? आमच्या सांस्कृतिक उद्दिष्टाचा भाग बनायचा आहे? आम्ही मराठी कलांचे संवर्धन आणि प्रोत्साहनाची आमची दृष्टी सामायिक करणार्या प्रतिभावान व्यक्तींचे स्वागत करतो.",
        applyNow: "आताच अर्ज करा - Google Form",
        tributeTo: "श्रद्धांजली",
        arpanaDesc: "स्व. डॉ. अपर्णा जोशी यांना श्रद्धांजली - स्वर्गीय डॉ. अपर्णा जोशी यांचा आत्मा आजही आमच्या कार्याचे मार्गदर्शन करणारा दीपस्तंभ आहे, आणि अस्मिता मराठी नाट्य सेवा संस्थेच्या प्रत्येक तालमीत व सादरीकरणामध्ये त्यांचा आवाज आजही घुमतो आहे. उज्जैन येथील माधव महाविद्यालयाच्या मराठी विभागाच्या माजी विभागप्रमुख असलेल्या डॉ. जोशी, केवळ आम्हाला साहित्य शिकवणाऱ्या शिक्षिका नव्हत्या; त्या आमच्यावर मनःपूर्वक प्रेम करणाऱ्या, आम्हाला आपल्या कुटुंबातील सदस्यांसारखे मानणाऱ्या, आणि समाजाच्या उत्तम हितासाठी कार्य करण्याची प्रेरणा देणाऱ्या आधारस्तंभ होत्या. त्यांनी आमच्या क्षमतेवर ठेवलेला तो अविचल विश्वास आणि प्रेमच आज आम्हाला मराठी कला जपण्यासाठी आणि त्यांना पुढे नेण्यासाठी प्रवृत्त करत आहे. परंतु, अत्यंत जड अंतःकरणाने आम्हाला हे आठवावे लागते की, त्यांच्या नाट्यविषयक आवडीचा कळस असलेल्या, त्यांनी दिग्दर्शित केलेल्या पहिल्या नाटकाचे मंचन त्या पाहू शकल्या नाहीत. त्यांचे ते अपूर्ण राहिलेले स्वप्न, त्यांच्या आयुष्यभराच्या नाट्यप्रेमाची ती साक्ष, आता आमच्यासाठी एक पवित्र जबाबदारी आहे. आज रंगमंचावर सादर केलेले प्रत्येक नाटक, आयोजित केलेली प्रत्येक कार्यशाळा, ही त्यांना आमची भावपूर्ण श्रद्धांजली आहे. त्यांनी जपलेली सुंदर सांस्कृतिक वारसा पुढील पिढीच्या हृदयात रुजेल, आणि दुर्दैवाने ज्या नाटकाचा पडदा त्या उचलू शकल्या नाहीत, ते यशस्वी होईल, हेच आमचे त्यांना वचन आहे. त्यांनी आमच्यावर केलेले अमर्याद प्रेम आणि त्यांनी दिलेली प्रेरणा यामुळेच आम्ही आज हे कार्य करण्यास सक्षम झालो आहोत."
    },
        navTitle: "अस्मिता मराठी नाट्य सेवा संस्था",
        home: "मुख्य",
        about: "हमारे बारे में",
        events: "कार्यक्रम",
        gallery: "गैलरी",
        contact: "संपर्क",
        title: "अस्मिता मराठी नाट्य सेवा संस्था<br>मराठी रंगमंच",
        location: "अस्मिता मराठी नाट्य सेवा संस्था, उज्जैन (म.प्र.)",
        regNo: "पंजीयन क्रमांक: 07/33/01/18504/24",
        description: "सामाजिक, पारिवारिक और प्रासंगिक नाटकों के माध्यम से सांस्कृतिक संरक्षण",
        joinUs: "हमसे जुड़ें",
        viewPrograms: "कार्यक्रम देखें",
        aboutUsTitle: "हमारे बारे में",
        aboutUsText: "अस्मिता मराठी नाट्य सेवा संस्था उज्जैन में मराठी रंगमंच को बढ़ावा देने के लिए समर्पित है। हमारा उद्देश्य पारंपरिक और आधुनिक मराठी नाटकों के माध्यम से सांस्कृतिक मूल्यों को संरक्षित करना है।",
        upcomingEvents: "आगामी कार्यक्रम",
        programGallery: "कार्यक्रम गैलरी",
        contactUs: "संपर्क करें",
        yourName: "आपका नाम",
        emailAddress: "ईमेल पता",
        message: "संदेश",
        sendMessage: "संदेश भेजें",
        mainPages: "मुख्य पृष्ठ",
        extras: "अतिरिक्त",
        privacyPolicy: "गोपनीयता नीति",
        adminPanel: "एडमिन पैनल",
        contactInfo: "संपर्क जानकारी", 
        copyright: "© 2024 अस्मिता मराठी नाट्य सेवा संस्था, उज्जैन म.प्र. सर्वाधिकार सुरक्षित।",
        privacy: "गोपनीयता",
        help: "सहायता",
        performances: "प्रदर्शन",
        artists: "कलाकार",
        experience: "वर्षों का अनुभव",
        // About Page
        aboutTitle: "परिचय - अस्मिता मराठी नाट्य सेवा संस्था",
        aboutHeroTitle: "हमारे बारे में",
        aboutHeroSubtitle: "मराठी नाट्य कला की समृद्ध परंपरा को आगे बढ़ाना",
        ourHistory: "हमारा इतिहास",
        ourMission: "हमारा उद्देश्य",
        ourVision: "हमारी दृष्टि",
        missionText: "मराठी भाषा और संस्कृति को जीवित रखना, नई प्रतिभाओं को मंच प्रदान करना, और समाज में कलात्मक चेतना विकसित करना हमारा मुख्य उद्देश्य है।",
        visionText: "एक ऐसा समाज बनाना जहाँ मराठी नाट्य कला फले-फूले और नई पीढ़ी इस समृद्ध विरासत से जुड़े। हम मानते हैं कि प्रत्येक व्यक्ति को कला के माध्यम से अपनी अभिव्यक्ति करनी चाहिए।",
        ourTeam: "हमारी टीम",
        founder: "संस्थापक एवं निदेशक",
        artisticDirector: "कलात्मक निदेशक",
        musicDirector: "संगीत निदेशक",
        // Contact Page
        contactTitle: "संपर्क - अस्मिता मराठी नाट्य सेवा संस्था",
        contactHeroTitle: "संपर्क करें",
        contactHeroSubtitle: "हमसे जुड़ें और मराठी नाट्य कला का हिस्सा बनें",
        contactInfoTitle: "संपर्क जानकारी",
        address: "पता",
        phone: "फोन",
        email: "ईमेल",
        timing: "समय",
        timingDetails: "सोमवार - शनिवार<br>सुबह 10:00 - शाम 6:00",
        sendMessageTitle: "संदेश भेजें",
        yourPhone: "फोन नंबर",
        socialMedia: "सोशल मीडिया",
        selectSubject: "विषय चुनें",
        subjectMembership: "सदस्यता",
        subjectPerformance: "प्रदर्शन",
        subjectWorkshop: "कार्यशाला",
        subjectCollaboration: "सहयोग",
        subjectOther: "अन्य",
        ourLocation: "हमारा स्थान",
        locationOnMap: "उज्जैन, मध्य प्रदेश में हमारा स्थान",
        joinUsTitle: "हमारे नाट्य परिवार में शामिल हों",
        joinUsDescription: "क्या आपको मराठी रंगमंच से प्रेम है? क्या आप हमारे सांस्कृतिक मिशन का हिस्सा बनना चाहते हैं? हम प्रतिभाशाली व्यक्तियों का स्वागत करते हैं जो मराठी कलाओं के संरक्षण और प्रोत्साहन की हमारी दृष्टि साझा करते हैं।",
        applyNow: "अभी आवेदन करें - Google Form",
        tributeTo: "श्रद्धांजलि",


    en: {
        navTitle: "Asmita Marathi Natya Seva Sanstha",
        home: "Home",
        about: "About Us",
        events: "Programs", 
        gallery: "Gallery", 
        contact: "Contact",
        ourFounders: "Our Founders",
        president: "President",
        secretary: "Secretary",
        member: "Member",
        girishDesc: "Leading the organization with passion for Marathi theatre and cultural preservation.",
        sudheerDesc: "Managing organizational activities and promoting theatre arts in the community.",
        neetaDesc: "Supporting cultural activities and women's participation in theatre arts.",
        title: "Asmita Marathi Natya Seva Sanstha<br>Marathi Theatre",
        location: "Asmita Marathi Natya Seva Sanstha, Ujjain (M.P.)",
        regNo: "Registration No: 07/33/01/18504/24",
        description: "Cultural preservation through social, family and situational dramas",
        joinUs: "Join Us",
        viewPrograms: "View Programs",
        aboutUsTitle: "About Us",
        aboutUsText: "Founded two years ago, Asmita Marathi Natya Seva Sanstha was born out of a deep passion to preserve and promote the Marathi language among the new generation and the wider community. Realizing that Marathi art and theatre were gradually losing their audience, our founders created an organization dedicated to keeping the richness of our mother tongue alive through impactful acts, dramas, and performances.",
        aboutUsText2: "We focus on theatre, workshops, stage performances, and street plays — in festivals, functions, and on-demand events — using every possible medium to make Marathi language meaningful and engaging, especially for children and young audiences. Our reach spans school children, college students, theatre enthusiasts, rural communities, and Marathi-speaking audiences everywhere, fostering a strong connection to culture and heritage.",
        aboutUsText3: "In just two years, we have performed in multiple cities, welcomed new actors into our fold, and ensured that both participants and the organization benefit sustainably. Beyond performances, we actively contribute to social awareness, nurturing talent, and spreading the love for Marathi theatre far and wide.",
        aboutUsText4: "Our vision is to preserve Marathi theatre and culture, expanding our reach across India to touch the hearts of all native Marathi speakers, ensuring that the beauty of our language and arts continues to inspire generations to come.",
        eventsSubtitle: "Our latest theatre performances and cultural programs",
        eventTypes: "Event Types",
        theatrePerformances: "Theatre Performances",
        theatreDesc: "Traditional and modern Marathi plays",
        workshops: "Workshops",
        workshopDesc: "Teaching acting and theatre techniques",
        festivalPrograms: "Festival Programs",
        festivalDesc: "Cultural presentations on special occasions",
        gallerySubtitle: "Glimpses of our memorable moments",
        videoGallery: "Video Gallery",
        sanskarPlay: "Theatre Performance - \"Sanskar\"",
        actingWorkshop: "Acting Workshop",
        culturalProgram: "Cultural Program",
        dharAugTitle: "Dhar - August 2025",
        ujjainSepTitle: "Ujjain - September 2025",
        noEventsMessage: "No upcoming events scheduled yet",
        checkBackMessage: "Please check back later for updates",
        emailUs: "Email Us",
        sendQueries: "Send us your queries",
        sendEmail: "Send Email",
        connectWithUs: "Connect with Us",
        chatInstantly: "Chat with our team instantly",
        visitUs: "Visit Us",
        findLocation: "Find us at our location",
        getDirections: "Get Directions",
        applyNow: "Apply Now",
        upcomingEvents: "Upcoming Events",
        programGallery: "Program Gallery",
        contactUs: "Contact Us",
        yourName: "Your Name",
        emailAddress: "Email Address",
        message: "Message",
        sendMessage: "Send Message",
        mainPages: "Main Pages",
        extras: "Extras",
        privacyPolicy: "Privacy Policy",
        adminPanel: "Admin Panel",
        contactInfo: "Contact Information", 
        copyright: "© 2024 Asmita Marathi Natya Seva Sanstha, Ujjain M.P. All Rights Reserved.",
        privacy: "Privacy",
        help: "Help",
        performances: "Performances",
        artists: "Artists",
        experience: "Years of Experience",
        // About Page
        aboutTitle: "About Us - Asmita Marathi Natya Seva Sanstha",
        aboutHeroTitle: "About Us",
        aboutHeroSubtitle: "Carrying forward the rich tradition of Marathi theatre art",
        ourFoundation: "Our Foundation",
        foundationText: "Founded two years ago, Asmita Marathi Natya Seva Sanstha was born out of a deep passion to preserve and promote the Marathi language among the new generation and the wider community. Realizing that Marathi art and theatre were gradually losing their audience, our founders created an organization dedicated to keeping the richness of our mother tongue alive through impactful acts, dramas, and performances.",
        ourApproach: "Our Approach",
        approachText: "We focus on theatre, workshops, stage performances, and street plays — in festivals, functions, and on-demand events — using every possible medium to make Marathi language meaningful and engaging, especially for children and young audiences. Our reach spans school children, college students, theatre enthusiasts, rural communities, and Marathi-speaking audiences everywhere, fostering a strong connection to culture and heritage.",
        ourImpact: "Our Impact & Vision",
        impactText: "In just two years, we have performed in multiple cities, welcomed new actors into our fold, and ensured that both participants and the organization benefit sustainably. Beyond performances, we actively contribute to social awareness, nurturing talent, and spreading the love for Marathi theatre far and wide. Our vision is to preserve Marathi theatre and culture, expanding our reach across India to touch the hearts of all native Marathi speakers, ensuring that the beauty of our language and arts continues to inspire generations to come.",
        missionText: "Our main objective is to keep the Marathi language and culture alive, provide a stage for new talent, and develop artistic consciousness in society.",
        visionText: "To create a society where Marathi theatre art flourishes and the new generation connects with this rich heritage. We believe that every individual should express themselves through art.",
        ourTeam: "Our Team",
        founder: "Founder & Director",
        artisticDirector: "Artistic Director",
        musicDirector: "Music Director",
        // Contact Page
        contactTitle: "Contact - Asmita Marathi Natya Seva Sanstha",
        contactHeroTitle: "Contact Us",
        contactHeroSubtitle: "Connect with us and be a part of Marathi theatre art",
        contactInfoTitle: "Contact Information",
        address: "Address",
        phone: "Phone",
        email: "Email",
        timing: "Hours",
        timingDetails: "Monday - Saturday<br>10:00 AM - 6:00 PM",
        sendMessageTitle: "Send a Message",
        yourPhone: "Phone Number",
        socialMedia: "Social Media",
        selectSubject: "Select Subject",
        subjectMembership: "Membership",
        subjectPerformance: "Performance",
        subjectWorkshop: "Workshop", 
        subjectCollaboration: "Collaboration",
        subjectOther: "Other",
        ourLocation: "Our Location",
        locationOnMap: "Our location in Ujjain, Madhya Pradesh",
        joinUsTitle: "Join Our Theatre Family",
        joinUsDescription: "Are you passionate about Marathi theatre? Do you want to be part of our cultural mission? We welcome talented individuals who share our vision of preserving and promoting Marathi arts.",
        applyNow: "Apply Now - Google Form",
        tributeTo: "Tribute To",
        arpanaDesc: "The spirit of Late Dr. Aparna Joshi remains the guiding soul of our mission, though her voice still echoes in every rehearsal and performance of the Asmita Marathi Natya Seva Sanstha. Dr. Joshi, our beloved Former Head of the Marathi Department at Madhav College, Ujjain, shared her heart with us; she loved us deeply, treating us not as students but as her own, and inspired in us the passion for the greater good of society. That affection, that unwavering belief she placed in our potential, is what compels us to fight for the survival of Marathi arts today. It is with a heavy heart we remember the profound tragedy that she passed away just before she could witness her first directed drama take the stage. That unfulfilled dream, a testament to her lifelong passion for theatre, is now a sacred trust. Every play we stage, every workshop we organize, is our solemn promise to her: we will ensure that the beautiful cultural legacy she cherished, and the curtain she was tragically unable to raise, will now thrive in the hearts of a new generation. We are who we are because of the indelible love and inspiration she left with us."
    }
};

let currentLang = 'en';

function switchLanguage(lang) {
    currentLang = lang;
    updateContent();
    localStorage.setItem('selectedLang', lang);
}

function updateContent() {
    const t = translations[currentLang];
    if (!t) return;

    // Update elements with data-key attributes
    document.querySelectorAll('[data-key]').forEach(el => {
        const key = el.getAttribute('data-key');
        if (t[key]) {
            if (['title', 'description', 'timingDetails'].includes(key)) {
                el.innerHTML = t[key];
            } else {
                el.textContent = t[key];
            }
        }
    });

    // Update page title
    const pageTitleKey = document.documentElement.getAttribute('data-page-title-key');
    if (pageTitleKey && t[pageTitleKey]) {
        document.title = t[pageTitleKey];
    }
    
    // Update language buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        const btnLang = btn.getAttribute('data-lang');
        if (btnLang === currentLang) {
            btn.classList.add('active');
        }
    });

    // Update html lang attribute
    document.documentElement.lang = currentLang;
}

document.addEventListener('DOMContentLoaded', () => {
    // Get saved language or default to English
    const savedLang = localStorage.getItem('selectedLang') || 'en';
    currentLang = savedLang;
    updateContent();
});